---
title: "Rapport TD6"
author: "Hafadhui DANIEL"
format: html
editor: visual
params:
  code_commune: "44109"
  code_departement: "44"
output: html_document
---

```{r}
options(repos = c(CRAN = "https://cloud.r-project.org"))
```

```{r}

library(remotes)

remotes::install_github("hafa-dnl/firstlibdaniel")

library(devtools)
library(firstlibdaniel)
library(dplyr)
library(ggplot2)
```

#### Introduction: chargement de la librairie et test avec paramètre

# Filtrer les données pour la commune spécifiée

```{r}
data_commune <- elus_conseillers_municipaux_cm %>%
  filter(Code.de.la.commune == params$code_commune)
data_commune <- creer_commune(data_commune)
plot_commune(data_commune)
```

```{r}
# Filtrer les données pour le département spécifié
data_departement <- creer_departement(elus_conseillers_municipaux_cm %>%
  filter(Code.du.departement == params$code_departement))

plot_departement(data_departement)

```

```{r}
summary_commune(data_commune)
summary_departement(data_departement)
```
